name: petal
description: "A clean, cross-platform media client built with Flutter — watch your favorite shows on Linux, Windows, Android, and iOS."
publish_to: 'none'

version: 0.3.1+31

environment:
  sdk: ^3.13.0

dependency_overrides:
  media_kit:
    git:
      url: https://github.com/Insight-Timer/media-kit.git
      ref: 37344b7f028d4048d8e02a9cb28109756d6aae95
      path: media_kit
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  media_kit:
    git:
      url: https://github.com/Insight-Timer/media-kit.git
      ref: 37344b7f028d4048d8e02a9cb28109756d6aae95
      path: media_kit
  media_kit_video:
    git:
      url: https://github.com/Insight-Timer/media-kit.git
      ref: 37344b7f028d4048d8e02a9cb28109756d6aae95
      path: media_kit_video
  media_kit_libs_ios_video:
    git:
      url: https://github.com/Insight-Timer/media-kit.git
      ref: 37344b7f028d4048d8e02a9cb28109756d6aae95
      path: libs/ios/media_kit_libs_ios_video
  media_kit_libs_android_video:
    git:
      url: https://github.com/Insight-Timer/media-kit.git
      ref: 37344b7f028d4048d8e02a9cb28109756d6aae95
      path: libs/android/media_kit_libs_android_video
  media_kit_libs_linux:
    git:
      url: https://github.com/Insight-Timer/media-kit.git
      ref: 37344b7f028d4048d8e02a9cb28109756d6aae95
      path: libs/linux/media_kit_libs_linux

  url_launcher: ^6.3.2
  cached_network_image: ^4.0.0
  path_provider: ^2.1.5
  package_info_plus: ^10.2.1
  fuzzywuzzy: ^1.2.0
  shadcn_flutter: ^0.0.54
  flutter_native_splash: ^2.4.7
  go_router: ^18.0.1
  dio: ^5.9.2
  cookie_jar: ^4.0.9
  dio_cookie_manager: ^3.4.0
  path: ^1.9.1
  window_manager: ^0.5.1
  rxdart: ^0.28.0
  collection: ^1.19.1
  sizer: ^3.1.3
  flutter_svg: ^2.2.4
  flutter_discord: ^1.2.1
  file_picker: ^12.3.0
  crop_your_image: ^2.0.0
  youtube_explode_dart: ^3.1.0
  skeletonizer: ^2.1.3
  mime: ^2.0.0
  shared_preferences: ^2.5.5
  flutter_cache_manager: ^3.4.2
  git_stamp: ^5.10.1
  web_socket_channel: ^3.0.3
  jwt_decoder: ^2.0.1
  archive: ^4.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: false
  assets:
    - assets/images/
